[theme]
# Primary accent color for interactive elements.
primaryColor = "#ff4b4b"

# Background color for the main content area.
backgroundColor = "#0E1117"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#31333F"

# Color used for almost all text.
textColor = "#ffffff"

[browser]
gatherUsageStats = false